# Generated by Django 5.2 on 2025-05-28 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=200)),
                ('quantidade', models.IntegerField()),
                ('borda', models.CharField(choices=[('0', 'Sem borda'), ('1', 'Catupiry'), ('2', 'Cheddar'), ('3', 'Doce de leite')], max_length=1)),
                ('tamanho', models.CharField(choices=[('0', 'Grande'), ('1', 'Médio'), ('2', 'Pequeno')], max_length=1)),
                ('sabor1', models.CharField(choices=[('01', 'Portuguesa'), ('02', 'Chocolate'), ('03', 'Peixe'), ('04', 'Margarita'), ('05', 'Quatro-queijos'), ('06', 'Marguerita'), ('07', 'Calabresa'), ('08', 'Peperoni'), ('09', 'Alho e óleo')], default='01', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(choices=[('01', 'Portuguesa'), ('02', 'Chocolate'), ('03', 'Peixe'), ('04', 'Margarita'), ('05', 'Quatro-queijos'), ('06', 'Marguerita'), ('07', 'Calabresa'), ('08', 'Peperoni'), ('09', 'Alho e óleo')], max_length=2)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='cliente.pedido')),
            ],
        ),
    ]
