# Generated by Django 5.2.1 on 2025-05-21 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=100)),
                ('cliente_cpf', models.CharField(max_length=14)),
                ('endereco', models.CharField(max_length=255)),
                ('borda', models.CharField(max_length=50)),
                ('preco_borda', models.DecimalField(decimal_places=2, max_digits=6)),
                ('tamanho', models.CharField(max_length=20)),
                ('preco_tamanho', models.DecimalField(decimal_places=2, max_digits=6)),
                ('quantidade', models.IntegerField()),
                ('valor_entrega', models.DecimalField(decimal_places=2, max_digits=6)),
                ('distancia_ajustada', models.FloatField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(max_length=50)),
                ('preco_sabor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=6)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='cliente.pedido')),
            ],
        ),
    ]
