# Generated by Django 5.2.1 on 2025-05-22 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='cliente_nome',
            new_name='nome',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='cliente_cpf',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='distancia_ajustada',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='preco_borda',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='preco_tamanho',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='valor_entrega',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cpf',
            field=models.CharField(default='00000000000', max_length=11),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='sabor1',
            field=models.CharField(choices=[('01', 'Portuguesa'), ('02', 'Chocolate'), ('03', 'Peixe'), ('04', 'Margarita'), ('05', 'Quatro-queijos'), ('06', 'Marguerita'), ('07', 'Calabresa'), ('08', 'Peperoni'), ('09', 'Alho e óleo')], default=0, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pedido',
            name='sabor2',
            field=models.CharField(blank=True, choices=[('01', 'Portuguesa'), ('02', 'Chocolate'), ('03', 'Peixe'), ('04', 'Margarita'), ('05', 'Quatro-queijos'), ('06', 'Marguerita'), ('07', 'Calabresa'), ('08', 'Peperoni'), ('09', 'Alho e óleo')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='borda',
            field=models.CharField(choices=[('0', 'Sem borda'), ('1', 'Catupiry'), ('2', 'Cheddar'), ('3', 'Doce de leite')], max_length=1),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='endereco',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tamanho',
            field=models.CharField(choices=[('0', 'Grande'), ('1', 'Médio'), ('2', 'Pequeno')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
