# Generated by Django 5.2.1 on 2025-05-22 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_rename_cliente_nome_pedido_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='sabor2',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='sabor1',
            field=models.CharField(choices=[('01', 'Portuguesa'), ('02', 'Chocolate'), ('03', 'Peixe'), ('04', 'Margarita'), ('05', 'Quatro-queijos'), ('06', 'Marguerita'), ('07', 'Calabresa'), ('08', 'Peperoni'), ('09', 'Alho e óleo')], default='01', max_length=2),
        ),
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sabor', models.CharField(choices=[('01', 'Portuguesa'), ('02', 'Chocolate'), ('03', 'Peixe'), ('04', 'Margarita'), ('05', 'Quatro-queijos'), ('06', 'Marguerita'), ('07', 'Calabresa'), ('08', 'Peperoni'), ('09', 'Alho e óleo')], max_length=2)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizzas', to='cliente.pedido')),
            ],
        ),
    ]
