# Generated by Django 5.2.1 on 2025-06-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0003_pedido_complemento_pedido_numero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='numero',
        ),
    ]
