# Generated by Django 5.2 on 2025-06-04 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0004_remove_pedido_complemento_remove_pedido_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='forma_de_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('debito', 'Cartão de Débito'), ('credito', 'Cartão de Crédito'), ('pix', 'PIX')], default=1, max_length=10, verbose_name='Forma de Pagamento'),
            preserve_default=False,
        ),
    ]
