# Generated by Django 5.2 on 2025-05-28 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_pedido_concluido'),
        ('funcionario', '0002_funcionario_concluido_funcionario_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='concluido',
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=100)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cliente.pedido')),
            ],
        ),
    ]
